/* Notes

Based on UTF-8
*/


# include "./calendar_af_za.h"
# include "./calendar_bg_bg.h"
# include "./calendar_br_fr.h"
# include "./calendar_ca_es.h"
# include "./calendar_cs_cz.h"
# include "./calendar_cy_gb.h"
# include "./calendar_da_dk.h"
# include "./calendar_de_de.h"
# include "./calendar_el_gr.h"
# include "./calendar_en.h"
# include "./calendar_es_es.h"
# include "./calendar_et_ee.h"
# include "./calendar_eu_es.h"
# include "./calendar_fi_fi.h"
# include "./calendar_fil_ph.h"
# include "./calendar_fr_fr.h"
# include "./calendar_ga_ie.h"
# include "./calendar_gd_gb.h"
# include "./calendar_gl_es.h"
# include "./calendar_gv_gb.h"
# include "./calendar_hr_hr.h"
# include "./calendar_hu_hu.h"
# include "./calendar_id_id.h"
# include "./calendar_is_is.h"
# include "./calendar_it_it.h"
# include "./calendar_ja_jp.h"
# include "./calendar_jv.h"
# include "./calendar_ll.h"
# include "./calendar_lt_lt.h"
# include "./calendar_lv_lv.h"
# include "./calendar_ms_my.h"
# include "./calendar_nb_no.h"
# include "./calendar_nl_nl.h"
# include "./calendar_nn_no.h"
# include "./calendar_pl_pl.h"
# include "./calendar_pt_pt.h"
# include "./calendar_rl.h"
# include "./calendar_ro_ro.h"
# include "./calendar_ru_ru.h"
# include "./calendar_sk_sk.h"
# include "./calendar_sq_al.h"
# include "./calendar_sv_se.h"
# include "./calendar_tk_tm.h"
# include "./calendar_to_to.h"
# include "./calendar_tr_tr.h"
# include "./calendar_zh_hans_cn.h"
