/* cals_e.h */

enum {
JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER,MONTHS,
};

enum {
SUNDAY,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,DAYS,
};

enum {
CALS_WK,CALS_DI,CALS_MO,CALS_YR,CALS_DATE,
};

enum {
CALS_SM,CALS_MN,CALS_HR,CALS_TIME,
};

enum {
CALS_PERIOD_THEDAY,
CALS_PERIOD_THEFIRST,
CALS_PERIOD_THESECOND,
CALS_PERIOD_THETHIRD,
CALS_PERIOD_THEFOURTH,
CALS_PERIOD_THELAST,
CALS_PERIOD_WORKWEEK,
CALS_PERIOD_WEEKEND,
CALS_PERIOD_THEDAYS,
};

enum {
THEFIRST,THELAST,
};
