enum {
CTRL_AT,CTRL_A,CTRL_B,CTRL_C,
CTRL_D,CTRL_E,CTRL_F,CTRL_G,
CTRL_H,CTRL_I,CTRL_J,CTRL_K,
CTRL_L,CTRL_M,CTRL_N,CTRL_O,
CTRL_P,CTRL_Q,CTRL_R,CTRL_S,
CTRL_T,CTRL_U,CTRL_V,CTRL_W,
CTRL_X,CTRL_Y,CTRL_Z,CTRL_LSB,
CTRL_RS,CTRL_RSB,CTRL_CA,CTRL_LL,
CTRL_KEYS,
};

enum {
NUL,SOH,STX,ETX,
EOT,ENQ,ACK,BEL,
BS,HT,LF,VT,
FF,CR,SO,SI,
DLE,DC1,DC2,DC3,
DC4,NAK,SYN,ETB,
CAN,EM,SUB,ESC,
FS,GS,RS,US,
SP,
};
